#!/bin/bash
# Script to verify cart database structure

echo "=== Cart System Database Verification ==="
echo ""
echo "This script checks if the cart system is working properly."
echo ""
echo "Steps to verify manually:"
echo ""
echo "1. LOGIN to the app at http://localhost:3000/login"
echo "2. Go to a product page"
echo "3. Click 'Add to Cart'"
echo "4. Open Browser DevTools (F12)"
echo "5. Go to Application → Cookies → Find 'authjs.session-token'"
echo "6. Note the session token"
echo ""
echo "7. Run this query in database to find the user ID:"
echo "   SELECT \"id\", \"email\" FROM \"User\" WHERE \"email\" = '[your-email]';"
echo ""
echo "8. Run this query to check cart:"
echo "   SELECT * FROM \"Cart\" WHERE \"userId\" = '[user-id]';"
echo ""
echo "9. Run this query to check cart items:"
echo "   SELECT \"id\", \"cartId\", \"productId\", \"variantId\", \"quantity\", \"unitPriceFils\" FROM \"CartItem\" WHERE \"cartId\" = '[cart-id]';"
echo ""
echo "10. The CartItem row should exist with quantity > 0"
echo "    If it doesn't exist, the POST /api/cart call failed"
echo ""
echo "Expected flow:"
echo "User clicks 'Add' → POST /api/cart → CartItem created in DB → Item shows in cart UI → Refresh → Still there"
echo ""
echo "To debug:"
echo "1. Check browser Network tab → POST /api/cart → Response should show cart with items"
echo "2. Check terminal output → Look for 'POST /api/cart 200' or '400'"
echo "3. If 400, look for error logs in terminal"
echo "4. Run: DEBUG_CHECKOUT=true npm run dev (for more logs)"
