/**
 * Complete list of countries with ISO 3166-1 alpha-2 codes and calling codes
 * Used for phone number validation and country selection
 */

export interface Country {
  iso2: string;
  name: string;
  callingCode: string;
}

export const ALL_COUNTRIES: Country[] = [
  { iso2: "AF", name: "Afghanistan", callingCode: "+93" },
  { iso2: "AL", name: "Albania", callingCode: "+355" },
  { iso2: "DZ", name: "Algeria", callingCode: "+213" },
  { iso2: "AD", name: "Andorra", callingCode: "+376" },
  { iso2: "AO", name: "Angola", callingCode: "+244" },
  { iso2: "AG", name: "Antigua and Barbuda", callingCode: "+1268" },
  { iso2: "AR", name: "Argentina", callingCode: "+54" },
  { iso2: "AM", name: "Armenia", callingCode: "+374" },
  { iso2: "AU", name: "Australia", callingCode: "+61" },
  { iso2: "AT", name: "Austria", callingCode: "+43" },
  { iso2: "AZ", name: "Azerbaijan", callingCode: "+994" },
  { iso2: "BS", name: "Bahamas", callingCode: "+1242" },
  { iso2: "BH", name: "Bahrain", callingCode: "+973" },
  { iso2: "BD", name: "Bangladesh", callingCode: "+880" },
  { iso2: "BB", name: "Barbados", callingCode: "+1246" },
  { iso2: "BY", name: "Belarus", callingCode: "+375" },
  { iso2: "BE", name: "Belgium", callingCode: "+32" },
  { iso2: "BZ", name: "Belize", callingCode: "+501" },
  { iso2: "BJ", name: "Benin", callingCode: "+229" },
  { iso2: "BT", name: "Bhutan", callingCode: "+975" },
  { iso2: "BO", name: "Bolivia", callingCode: "+591" },
  { iso2: "BA", name: "Bosnia and Herzegovina", callingCode: "+387" },
  { iso2: "BW", name: "Botswana", callingCode: "+267" },
  { iso2: "BR", name: "Brazil", callingCode: "+55" },
  { iso2: "BN", name: "Brunei", callingCode: "+673" },
  { iso2: "BG", name: "Bulgaria", callingCode: "+359" },
  { iso2: "BF", name: "Burkina Faso", callingCode: "+226" },
  { iso2: "BI", name: "Burundi", callingCode: "+257" },
  { iso2: "KH", name: "Cambodia", callingCode: "+855" },
  { iso2: "CM", name: "Cameroon", callingCode: "+237" },
  { iso2: "CA", name: "Canada", callingCode: "+1" },
  { iso2: "CV", name: "Cape Verde", callingCode: "+238" },
  { iso2: "CF", name: "Central African Republic", callingCode: "+236" },
  { iso2: "TD", name: "Chad", callingCode: "+235" },
  { iso2: "CL", name: "Chile", callingCode: "+56" },
  { iso2: "CN", name: "China", callingCode: "+86" },
  { iso2: "CO", name: "Colombia", callingCode: "+57" },
  { iso2: "KM", name: "Comoros", callingCode: "+269" },
  { iso2: "CG", name: "Congo", callingCode: "+242" },
  { iso2: "CD", name: "Congo (DRC)", callingCode: "+243" },
  { iso2: "CR", name: "Costa Rica", callingCode: "+506" },
  { iso2: "HR", name: "Croatia", callingCode: "+385" },
  { iso2: "CU", name: "Cuba", callingCode: "+53" },
  { iso2: "CY", name: "Cyprus", callingCode: "+357" },
  { iso2: "CZ", name: "Czech Republic", callingCode: "+420" },
  { iso2: "DK", name: "Denmark", callingCode: "+45" },
  { iso2: "DJ", name: "Djibouti", callingCode: "+253" },
  { iso2: "DM", name: "Dominica", callingCode: "+1767" },
  { iso2: "DO", name: "Dominican Republic", callingCode: "+1809" },
  { iso2: "EC", name: "Ecuador", callingCode: "+593" },
  { iso2: "EG", name: "Egypt", callingCode: "+20" },
  { iso2: "SV", name: "El Salvador", callingCode: "+503" },
  { iso2: "GQ", name: "Equatorial Guinea", callingCode: "+240" },
  { iso2: "ER", name: "Eritrea", callingCode: "+291" },
  { iso2: "EE", name: "Estonia", callingCode: "+372" },
  { iso2: "ET", name: "Ethiopia", callingCode: "+251" },
  { iso2: "FJ", name: "Fiji", callingCode: "+679" },
  { iso2: "FI", name: "Finland", callingCode: "+358" },
  { iso2: "FR", name: "France", callingCode: "+33" },
  { iso2: "GA", name: "Gabon", callingCode: "+241" },
  { iso2: "GM", name: "Gambia", callingCode: "+220" },
  { iso2: "GE", name: "Georgia", callingCode: "+995" },
  { iso2: "DE", name: "Germany", callingCode: "+49" },
  { iso2: "GH", name: "Ghana", callingCode: "+233" },
  { iso2: "GR", name: "Greece", callingCode: "+30" },
  { iso2: "GD", name: "Grenada", callingCode: "+1473" },
  { iso2: "GT", name: "Guatemala", callingCode: "+502" },
  { iso2: "GN", name: "Guinea", callingCode: "+224" },
  { iso2: "GW", name: "Guinea-Bissau", callingCode: "+245" },
  { iso2: "GY", name: "Guyana", callingCode: "+592" },
  { iso2: "HT", name: "Haiti", callingCode: "+509" },
  { iso2: "HN", name: "Honduras", callingCode: "+504" },
  { iso2: "HU", name: "Hungary", callingCode: "+36" },
  { iso2: "IS", name: "Iceland", callingCode: "+354" },
  { iso2: "IN", name: "India", callingCode: "+91" },
  { iso2: "ID", name: "Indonesia", callingCode: "+62" },
  { iso2: "IR", name: "Iran", callingCode: "+98" },
  { iso2: "IQ", name: "Iraq", callingCode: "+964" },
  { iso2: "IE", name: "Ireland", callingCode: "+353" },
  { iso2: "IL", name: "Israel", callingCode: "+972" },
  { iso2: "IT", name: "Italy", callingCode: "+39" },
  { iso2: "CI", name: "Ivory Coast", callingCode: "+225" },
  { iso2: "JM", name: "Jamaica", callingCode: "+1876" },
  { iso2: "JP", name: "Japan", callingCode: "+81" },
  { iso2: "JO", name: "Jordan", callingCode: "+962" },
  { iso2: "KZ", name: "Kazakhstan", callingCode: "+7" },
  { iso2: "KE", name: "Kenya", callingCode: "+254" },
  { iso2: "KI", name: "Kiribati", callingCode: "+686" },
  { iso2: "KW", name: "Kuwait", callingCode: "+965" },
  { iso2: "KG", name: "Kyrgyzstan", callingCode: "+996" },
  { iso2: "LA", name: "Laos", callingCode: "+856" },
  { iso2: "LV", name: "Latvia", callingCode: "+371" },
  { iso2: "LB", name: "Lebanon", callingCode: "+961" },
  { iso2: "LS", name: "Lesotho", callingCode: "+266" },
  { iso2: "LR", name: "Liberia", callingCode: "+231" },
  { iso2: "LY", name: "Libya", callingCode: "+218" },
  { iso2: "LI", name: "Liechtenstein", callingCode: "+423" },
  { iso2: "LT", name: "Lithuania", callingCode: "+370" },
  { iso2: "LU", name: "Luxembourg", callingCode: "+352" },
  { iso2: "MK", name: "Macedonia", callingCode: "+389" },
  { iso2: "MG", name: "Madagascar", callingCode: "+261" },
  { iso2: "MW", name: "Malawi", callingCode: "+265" },
  { iso2: "MY", name: "Malaysia", callingCode: "+60" },
  { iso2: "MV", name: "Maldives", callingCode: "+960" },
  { iso2: "ML", name: "Mali", callingCode: "+223" },
  { iso2: "MT", name: "Malta", callingCode: "+356" },
  { iso2: "MH", name: "Marshall Islands", callingCode: "+692" },
  { iso2: "MR", name: "Mauritania", callingCode: "+222" },
  { iso2: "MU", name: "Mauritius", callingCode: "+230" },
  { iso2: "MX", name: "Mexico", callingCode: "+52" },
  { iso2: "FM", name: "Micronesia", callingCode: "+691" },
  { iso2: "MD", name: "Moldova", callingCode: "+373" },
  { iso2: "MC", name: "Monaco", callingCode: "+377" },
  { iso2: "MN", name: "Mongolia", callingCode: "+976" },
  { iso2: "ME", name: "Montenegro", callingCode: "+382" },
  { iso2: "MA", name: "Morocco", callingCode: "+212" },
  { iso2: "MZ", name: "Mozambique", callingCode: "+258" },
  { iso2: "MM", name: "Myanmar", callingCode: "+95" },
  { iso2: "NA", name: "Namibia", callingCode: "+264" },
  { iso2: "NR", name: "Nauru", callingCode: "+674" },
  { iso2: "NP", name: "Nepal", callingCode: "+977" },
  { iso2: "NL", name: "Netherlands", callingCode: "+31" },
  { iso2: "NZ", name: "New Zealand", callingCode: "+64" },
  { iso2: "NI", name: "Nicaragua", callingCode: "+505" },
  { iso2: "NE", name: "Niger", callingCode: "+227" },
  { iso2: "NG", name: "Nigeria", callingCode: "+234" },
  { iso2: "KP", name: "North Korea", callingCode: "+850" },
  { iso2: "NO", name: "Norway", callingCode: "+47" },
  { iso2: "OM", name: "Oman", callingCode: "+968" },
  { iso2: "PK", name: "Pakistan", callingCode: "+92" },
  { iso2: "PW", name: "Palau", callingCode: "+680" },
  { iso2: "PS", name: "Palestine", callingCode: "+970" },
  { iso2: "PA", name: "Panama", callingCode: "+507" },
  { iso2: "PG", name: "Papua New Guinea", callingCode: "+675" },
  { iso2: "PY", name: "Paraguay", callingCode: "+595" },
  { iso2: "PE", name: "Peru", callingCode: "+51" },
  { iso2: "PH", name: "Philippines", callingCode: "+63" },
  { iso2: "PL", name: "Poland", callingCode: "+48" },
  { iso2: "PT", name: "Portugal", callingCode: "+351" },
  { iso2: "QA", name: "Qatar", callingCode: "+974" },
  { iso2: "RO", name: "Romania", callingCode: "+40" },
  { iso2: "RU", name: "Russia", callingCode: "+7" },
  { iso2: "RW", name: "Rwanda", callingCode: "+250" },
  { iso2: "KN", name: "Saint Kitts and Nevis", callingCode: "+1869" },
  { iso2: "LC", name: "Saint Lucia", callingCode: "+1758" },
  { iso2: "VC", name: "Saint Vincent and the Grenadines", callingCode: "+1784" },
  { iso2: "WS", name: "Samoa", callingCode: "+685" },
  { iso2: "SM", name: "San Marino", callingCode: "+378" },
  { iso2: "ST", name: "Sao Tome and Principe", callingCode: "+239" },
  { iso2: "SA", name: "Saudi Arabia", callingCode: "+966" },
  { iso2: "SN", name: "Senegal", callingCode: "+221" },
  { iso2: "RS", name: "Serbia", callingCode: "+381" },
  { iso2: "SC", name: "Seychelles", callingCode: "+248" },
  { iso2: "SL", name: "Sierra Leone", callingCode: "+232" },
  { iso2: "SG", name: "Singapore", callingCode: "+65" },
  { iso2: "SK", name: "Slovakia", callingCode: "+421" },
  { iso2: "SI", name: "Slovenia", callingCode: "+386" },
  { iso2: "SB", name: "Solomon Islands", callingCode: "+677" },
  { iso2: "SO", name: "Somalia", callingCode: "+252" },
  { iso2: "ZA", name: "South Africa", callingCode: "+27" },
  { iso2: "KR", name: "South Korea", callingCode: "+82" },
  { iso2: "SS", name: "South Sudan", callingCode: "+211" },
  { iso2: "ES", name: "Spain", callingCode: "+34" },
  { iso2: "LK", name: "Sri Lanka", callingCode: "+94" },
  { iso2: "SD", name: "Sudan", callingCode: "+249" },
  { iso2: "SR", name: "Suriname", callingCode: "+597" },
  { iso2: "SZ", name: "Swaziland", callingCode: "+268" },
  { iso2: "SE", name: "Sweden", callingCode: "+46" },
  { iso2: "CH", name: "Switzerland", callingCode: "+41" },
  { iso2: "SY", name: "Syria", callingCode: "+963" },
  { iso2: "TW", name: "Taiwan", callingCode: "+886" },
  { iso2: "TJ", name: "Tajikistan", callingCode: "+992" },
  { iso2: "TZ", name: "Tanzania", callingCode: "+255" },
  { iso2: "TH", name: "Thailand", callingCode: "+66" },
  { iso2: "TL", name: "Timor-Leste", callingCode: "+670" },
  { iso2: "TG", name: "Togo", callingCode: "+228" },
  { iso2: "TO", name: "Tonga", callingCode: "+676" },
  { iso2: "TT", name: "Trinidad and Tobago", callingCode: "+1868" },
  { iso2: "TN", name: "Tunisia", callingCode: "+216" },
  { iso2: "TR", name: "Turkey", callingCode: "+90" },
  { iso2: "TM", name: "Turkmenistan", callingCode: "+993" },
  { iso2: "TV", name: "Tuvalu", callingCode: "+688" },
  { iso2: "UG", name: "Uganda", callingCode: "+256" },
  { iso2: "UA", name: "Ukraine", callingCode: "+380" },
  { iso2: "AE", name: "United Arab Emirates", callingCode: "+971" },
  { iso2: "GB", name: "United Kingdom", callingCode: "+44" },
  { iso2: "US", name: "United States", callingCode: "+1" },
  { iso2: "UY", name: "Uruguay", callingCode: "+598" },
  { iso2: "UZ", name: "Uzbekistan", callingCode: "+998" },
  { iso2: "VU", name: "Vanuatu", callingCode: "+678" },
  { iso2: "VA", name: "Vatican City", callingCode: "+379" },
  { iso2: "VE", name: "Venezuela", callingCode: "+58" },
  { iso2: "VN", name: "Vietnam", callingCode: "+84" },
  { iso2: "YE", name: "Yemen", callingCode: "+967" },
  { iso2: "ZM", name: "Zambia", callingCode: "+260" },
  { iso2: "ZW", name: "Zimbabwe", callingCode: "+263" },
];

/**
 * Get country by ISO2 code
 */
export function getCountryByIso2(iso2: string): Country | undefined {
  return ALL_COUNTRIES.find((c) => c.iso2 === iso2.toUpperCase());
}

/**
 * Get country by calling code
 */
export function getCountryByCallingCode(callingCode: string): Country | undefined {
  return ALL_COUNTRIES.find((c) => c.callingCode === callingCode);
}

/**
 * Search countries by name (case-insensitive)
 */
export function searchCountries(query: string): Country[] {
  const lowerQuery = query.toLowerCase();
  return ALL_COUNTRIES.filter((c) => c.name.toLowerCase().includes(lowerQuery));
}
